import json
from pathlib import Path

path = Path("data/series/index.json")
data = json.loads(path.read_text(encoding="utf-8"))
additions = [
    {"id":"the-1-percent-club-2022","type":"series","title":"The 1% Club","yearStart":2022,"yearEnd":2026,"seasonCount":5,"episodeCount":71,"scoringEntryCount":71,"genres":["Game Show"],"actors":["Lee Mack"],"audio":{"layouts":["Stereo"],"lossless":False},"description":"Lee Mack hosts a logic quiz in which one hundred contestants face questions ordered by how many members of the public answered them correctly. The problems rely on observation, language, numbers and lateral thinking rather than specialist trivia, with the surviving finalists eventually facing a question only one percent of the test sample solved.","score":None,"questionsVersion":"tv-v1","runtimeSeconds":194167,"seasons":[{"number":1,"yearStart":2022,"yearEnd":2022,"episodeCount":8,"scoringEntryCount":8,"audio":{"layouts":["Stereo"],"lossless":False}},{"number":2,"yearStart":2023,"yearEnd":2023,"episodeCount":8,"scoringEntryCount":8,"audio":{"layouts":["Stereo"],"lossless":False}},{"number":3,"yearStart":2023,"yearEnd":2024,"episodeCount":17,"scoringEntryCount":17,"audio":{"layouts":["Stereo"],"lossless":False}},{"number":4,"yearStart":2024,"yearEnd":2025,"episodeCount":18,"scoringEntryCount":18,"audio":{"layouts":["Stereo"],"lossless":False}},{"number":5,"yearStart":2025,"yearEnd":2026,"episodeCount":20,"scoringEntryCount":20,"audio":{"layouts":["Stereo"],"lossless":False}}]},
    {"id":"the-orville-2017","type":"series","title":"The Orville","yearStart":2017,"yearEnd":2022,"seasonCount":3,"episodeCount":36,"scoringEntryCount":36,"genres":["Science Fiction","Adventure","Comedy","Drama"],"actors":["Seth MacFarlane","Adrianne Palicki","Penny Johnson Jerald","Scott Grimes","Peter Macon","J. Lee","Mark Jackson"],"audio":{"layouts":["5.1"],"lossless":False},"description":"Captain Ed Mercer takes command of the exploratory vessel Orville with his ex-wife Kelly Grayson as first officer, leading a mixed human and alien crew through first contact, Union politics, hostile Krill space and increasingly difficult questions about artificial life, culture and identity. What begins as an awkward workplace posting grows into a wide-ranging mission across a changing interstellar alliance.","score":None,"questionsVersion":"tv-v1","runtimeSeconds":115677,"seasons":[{"number":1,"yearStart":2017,"yearEnd":2017,"episodeCount":12,"scoringEntryCount":12,"audio":{"layouts":["5.1"],"lossless":False}},{"number":2,"yearStart":2018,"yearEnd":2019,"episodeCount":14,"scoringEntryCount":14,"audio":{"layouts":["5.1"],"lossless":False}},{"number":3,"yearStart":2022,"yearEnd":2022,"episodeCount":10,"scoringEntryCount":10,"audio":{"layouts":["5.1"],"lossless":False}}]},
]
existing = {item.get("id") for item in data.get("series", [])}
for item in additions:
    if item["id"] not in existing:
        data.setdefault("series", []).append(item)
path.write_text(json.dumps(data, ensure_ascii=False, separators=(",", ":")) + "\n", encoding="utf-8")
